### PR TITLE
Fix runtime (part of the Bottles runtime fix effort)

### PR DESCRIPTION
**Pull request by koplo199**
Part of the Bottles runtime fix effort, see https://github.com/bottlesdevs/Bottles/issues/3054.

This PR is blocked by:
- https://github.com/bottlesdevs/build-tools/pull/6

Marking as draft as a result, but technically ready for review.

### CODE REVIEW

**Comment by mirkobrombin** [comment]
LGTM, is this ready to be merged?

**Comment by koplo199** [comment]
@mirkobrombin Yes it is. Btw, I joined the discord and sent you a DM 👍

**Comment by mirkobrombin** [comment]
> @mirkobrombin Yes it is. Btw, I joined the discord and sent you a DM 👍

What's your username? I have an almost endless list of chats to read :D

**Comment by koplo199** [comment]
@mirkobrombin Well, that's the price of success I guess 😅 My discord username is also koplo199, you can't go wrong

**Pull request merged**
